apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace.name }}-svc"
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
      {{- with .Values.labels }}
      {{- toYaml . | nindent 8 }}  # Indented properly for matchLabels
      {{- end }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}