name: Build and Push to ECR
run-name: Build N Deploy BWT-Sandbox by @${{ github.actor }} 🚀


on:
  push:
    branches: [main]
  merge_group:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      API_REPO_NAME: eu-prod_hellobible_api
      EKS_API_SECRET_NAME: hellobibleapi
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::905418367633:role/bwt-pe-github-auth-role

      - name: Auth Testing
        run: |
            aws sts get-caller-identity
        
        
